name: release

on:
  push:
    tags:
      - "**"

jobs:
  terUpload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: tomasnorre/typo3-upload-ter@v2.0.7
        with:
          api-token: ${{ secrets.TYPO3_API_TOKEN }}
